# Generated by Django 3.2.3 on 2021-07-04 14:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myblog', '0026_alter_post_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='profile_pics')),
                ('cover_img', models.ImageField(default='default.jpg', upload_to='cover_pics')),
                ('about', models.TextField(verbose_name=django.contrib.auth.models.User)),
                ('fb', models.URLField(blank=True, default='', max_length=255, null=True)),
                ('insta', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('fav_cat', models.ManyToManyField(related_name='fav_cat', to='myblog.Category')),
                ('fav_post', models.ManyToManyField(related_name='fav_post', to='myblog.Post')),
                ('followers', models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
