# Generated by Django 3.2.3 on 2021-07-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_img',
            field=models.ImageField(default='default_thumb.jpg', upload_to='cover_pics'),
        ),
    ]
