# Generated by Django 3.2.3 on 2021-07-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_img',
            field=models.ImageField(default=None, upload_to='cover_pics'),
        ),
    ]
