# Generated by Django 3.2.3 on 2021-07-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinus',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
