# Generated by Django 3.2.3 on 2021-07-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_joinus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinus',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
