# Generated by Django 3.2.3 on 2021-07-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_joinus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinus',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Person with this Email already exists.'}, max_length=254, unique=True),
        ),
    ]
