# Generated by Django 3.1.5 on 2021-04-13 18:45

from django.db import migrations, models
import myblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='cat',
            field=models.CharField(default='None', max_length=100, verbose_name=myblog.models.Category),
        ),
    ]
