# Generated by Django 3.1.5 on 2021-04-14 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0009_auto_20210414_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cmnt_likes',
            field=models.ManyToManyField(related_name='blog_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
