# Generated by Django 3.1.5 on 2021-04-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_remove_comment_cmnt_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
