# Generated by Django 3.1.5 on 2021-04-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
