# Generated by Django 3.1.5 on 2021-04-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0016_auto_20210415_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
