# Generated by Django 3.1.5 on 2021-05-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0022_auto_20210524_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(default='default_thumb.jpg', upload_to='category'),
        ),
    ]
