# Generated by Django 3.2.3 on 2021-07-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0026_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_img',
        ),
    ]
