# Generated by Django 3.2.3 on 2021-07-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0027_remove_category_cat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(default='default_thumb.jpg', upload_to='category'),
        ),
    ]
