# Generated by Django 3.2.3 on 2021-07-12 15:21

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('myblog', '0028_category_cat_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='post_tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
