# Generated by Django 3.1.5 on 2021-05-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
